export const FETCH_ROVERS = 'FETCH_ROVERS';
export const FETCH_ROVERS_PENDING = 'FETCH_ROVERS_PENDING';
export const FETCH_ROVERS_FULFILLED = 'FETCH_ROVERS_FULFILLED';
export const FETCH_ROVERS_REJECTED = 'FETCH_ROVERS_REJECTED';

export const FETCH_ROVER_PHOTOS = 'FETCH_ROVER_PHOTOS';
export const FETCH_ROVER_PHOTOS_PENDING = 'FETCH_ROVER_PHOTOS_PENDING';
export const FETCH_ROVER_PHOTOS_FULFILLED = 'FETCH_ROVER_PHOTOS_FULFILLED';
export const FETCH_ROVER_PHOTOS_REJECTED = 'FETCH_ROVER_PHOTOS_REJECTED';

export const FETCH_DATES = 'FETCH_DATES';
export const FETCH_DATES_PENDING = 'FETCH_DATES_PENDING';
export const FETCH_DATES_FULFILLED = 'FETCH_DATES_FULFILLED';
export const FETCH_DATES_REJECTED = 'FETCH_DATES_REJECTED';